version: '3'

services:
  web:
    build: .
    container_name: django
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    env_file:
      - ./.env

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data/:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      # MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      # MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}

volumes:
  mongo_data:
